# Generated by Django 4.0 on 2021-12-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_post_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
